stages:
  - test
  - deploy

test:
  image: oven/bun:alpine
  stage: test
  script:
    - npm install
    - bun lint
    - bun run build

pages:
  image: oven/bun:alpine
  stage: deploy
  script:
    - bun install
    - bun run build
    - echo "/* /index.html 200" > public/_redirects
  artifacts:
    paths:
      - public
  only:
    - main
