stages:
  - test
  - deploy

test:
  image: library/node:latest
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run build

pages:
  image: library/node:latest
  stage: deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - main
